-- Telemetry events. See docs/PRIVACY.md for the full schema rationale.
CREATE TABLE IF NOT EXISTS events (
  id           TEXT PRIMARY KEY,                    -- uuid generated by the Worker on insert
  device_id    TEXT NOT NULL,                       -- anon UUIDv4 from the client
  event_type   TEXT NOT NULL,                       -- whitelisted name (see ingest.ts)
  ts           INTEGER NOT NULL,                    -- client timestamp, seconds since epoch, server-clamped
  payload_json TEXT NOT NULL DEFAULT '{}',          -- structured event-specific data, capped at 4KB
  app_version  TEXT NOT NULL                        -- e.g. "0.4.0"
);

CREATE INDEX IF NOT EXISTS idx_events_type_ts   ON events(event_type, ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_device_ts ON events(device_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_ts        ON events(ts DESC);
